### PR TITLE
fix: fixed header file , ITM gwalior was overlapping

### LINKED ISSUE #101: 🐛 Bug Report: The logo is of GDSC is overlapping a bit with ITM gwalior header in the navbar
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The GDSC text if overlapping a bit with ITM gwalior text

### Expected Behavior

There should be some padding between the two and should look better

### Steps To Reproduce

just adding some padding between the two 

### Anything else?

gssic

### What browsers are you seeing the problem on?

Chrome

### PR DESCRIPTION
**Pull request by ArslanYM**
**Notes for Reviewers**

This PR fixes #101 

Describe the changes you've made:
adding padding to the top , which downshifts the `ITM gwalior` text a bit. Works perfectly for mobile and pc after fix  

Screenshots for the change:
-BEFORE: 

before

-AFTER:

fix1

### CODE REVIEW

File: src/Components/Header.js [hunk 1]
```diff
@@ -40,6 +40,7 @@ export default function Header(props) {
                 color: "#959595",
                 fontSize: "14.74px",
                 fontFamily: "Roboto",
+                paddingTop: "2px",
```
Comment (Yashsharma1911) [inline src/Components/Header.js:43]: I think 3 px will be nice @ArslanYM 
```suggestion
                paddingTop: "3px",
```

**Review by Yashsharma1911 — CHANGES_REQUESTED** [review]

**Comment by Yashsharma1911** [comment]
thanks for fixing @ArslanYM 🚀

**Comment by Yashsharma1911** [comment]
@ArslanYM we have other same-related issues in which you can help let me know if you need any help in finding them
