### PR TITLE
Changed cards design for Event section

### LINKED ISSUE #38: 🐛 Bug Report: Event section design should be change for small screen devices.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The event section should be responsive for mobile screen.
image

### Expected Behavior

image

checkout this design file - [Check Figma Design](https://www.figma.com/file/ZTnjjETRtg8HNV0zufJajF/GDSC?node-id=0%3A1&t=oEpdFbAdYoxhSJau-0) 

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### What browsers are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by martinyis**
This PR fixes #38
I wanted to give you an update on the design of our cards. I know I initially tried to create responsive cards using the design in Figma, but I ran into some issues along the way. So, I had to create a new file and start from scratch with a separate design for the cards.

I did my best to make the cards as similar to the original design as possible, but I want to make sure you're happy with the end result. If there's anything you want me to change, just let me know! I always appreciate your feedback and want to make sure I'm meeting your expectations.

Thanks for your patience and support while I work through these challenges.
BEFORE:

image
 AFTER:
 
 
image

### CODE REVIEW

**Comment by ArunPatel02** [comment]
Looking good @martinyis , would you please decrease the spacing between two cards

**Comment by martinyis** [comment]
> Looking good @martinyis , would you please decrease the spacing between two cards

Yup, check out the new commit.

**Review by ArunPatel02 — CHANGES_REQUESTED** [review]
thank a lot @martinyis for your wonderful contribution there are some requested changes can you please look into these changes.
1. would you please canter date vertically 
2. increase the width of card little bit
3. add time to the right of event name

**current behavior**
image

**expected behavior**
image

**Comment by martinyis** [comment]
@ArunPatel02 I just made a new commit with center date data and increased size. There is no data for a time in the Event.js pastData array. Do you want me to add just the default value or what should I do?

**Comment by ArunPatel02** [comment]
> @ArunPatel02 I just made a new commit with center date data and increased size. There is no data for a time in the Event.js pastData array. Do you want me to add just the default value or what should I do?

For now @martinyis add default value ( 10 -- 11 am)

File: src/Pages/Event/Event.js [hunk 1]
```diff
@@ -1,100 +1,197 @@
...
+    },
+    {
+      id: "2",
+      date: "12",
+      month: "jan 23",
+      topic: "Orientation Session",
+      text: "We are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students Clubs",
+      topImage: "/images/bg2.png",
+      color: "#f27770",
+    },
```
Comment (Yashsharma1911) [inline src/Pages/Event/Event.js:86]: @kamalchakma1 that's what I am talking about although I thought it was hard coded but we can move this to sperate file create issue for this it will be helpful

Comment (kamalchakma1) [reply src/Pages/Event/Event.js:86]: ok i got your point. let me create an issue on this.

**Comment by martinyis** [comment]
> > @ArunPatel02 I just made a new commit with center date data and increased size. There is no data for a time in the Event.js pastData array. Do you want me to add just the default value or what should I do?
> 
> For now @martinyis add default value ( 10 -- 11 am)

Alright, will finish in the morning!

**Comment by martinyis** [comment]
> > @ArunPatel02 I just made a new commit with center date data and increased size. There is no data for a time in the Event.js pastData array. Do you want me to add just the default value or what should I do?
> 
> For now @martinyis add default value ( 10 -- 11 am)

Hey, I just made a new commit with changes, take a look!

**Comment by Yashsharma1911** [comment]
@ArunPatel02 can we merge this PR?

**Review by ArunPatel02 — APPROVED** [review]

**Review by kamalchakma1 — APPROVED** [review]

**Comment by ArunPatel02** [comment]
> @ArunPatel02 can we merge this PR?

yes @Yashsharma1911  we can merge this pr.

**Comment by Yashsharma1911** [comment]
thanks @martinyis @ArunPatel02 @kamalchakma1
